version: '3'

services:
  app:    
    container_name: starwars
    build: .
    ports:
      - 8081:${HTTP_PORT}
    volumes:
      - .:/go/src
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    env_file:
      - .env
  
  redis:
    image: redis:alpine
    ports:
      - 6380:6380
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass $${REDIS_PASSWORD}
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    env_file:
      - .env
  
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_MONGODB}
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    env_file:
      - .env