// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/lucasd-coder/star-wars/config"
	"github.com/lucasd-coder/star-wars/internal/infra/repository"
	"github.com/lucasd-coder/star-wars/internal/pkg/mongodb"
	"github.com/lucasd-coder/star-wars/internal/service"
)

// Injectors from wire.go:

func InitializePlanetRepository() *repository.PlanetRepository {
	configConfig := config.GetConfig()
	client := mongodb.GetClientMongoDB()
	planetRepository := repository.NewPlanetRepository(configConfig, client)
	return planetRepository
}

func InitializeCreatePlanetService() *service.CreatePlanetService {
	planetRepository := InitializePlanetRepository()
	createPlanetService := service.NewCreatePlanetService(planetRepository)
	return createPlanetService
}
